package es.unizar.eina.T202_camping.database;

import android.app.Application;

public class SobTest {
    private CampingRepository mRepository;
    public static void ejecutar(Application application) {
        CampingRepository mRepository = new CampingRepository(application);
        long fallo = 0;
        int i = 0;
        String descripcion = "sobrecarga";
        while (fallo != -1) {
            int nParcela = i+1;
            Parcela pAux = new Parcela("parcela" + nParcela, descripcion, 5.5, 50);
            fallo = mRepository.insert(pAux);
            android.util.Log.d("Tamaño", String.valueOf(descripcion.length()));
            descripcion += "sobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecargasobrecarga";
            i++;
        }
    }
}
